// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJtG74ZkvA39Z0tiAVZYsBwR5vz1VAuA',
    appId: '1:288364669297:web:b7c7255224189585deeed0',
    messagingSenderId: '288364669297',
    projectId: 'iti-training-f15e2',
    authDomain: 'iti-training-f15e2.firebaseapp.com',
    storageBucket: 'iti-training-f15e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pQAXDQ__i_DnI3oYid4S0ZeF7UdBjd4',
    appId: '1:288364669297:android:3a21d128680f9cc8deeed0',
    messagingSenderId: '288364669297',
    projectId: 'iti-training-f15e2',
    storageBucket: 'iti-training-f15e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYkQ_NiYx4daUvfYyZL51AOmBxXiFnosE',
    appId: '1:288364669297:ios:a0ee14ba25ff65e8deeed0',
    messagingSenderId: '288364669297',
    projectId: 'iti-training-f15e2',
    storageBucket: 'iti-training-f15e2.appspot.com',
    iosClientId: '288364669297-a2q21c4gmq3ja9artejn0cmac2n2s4fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYkQ_NiYx4daUvfYyZL51AOmBxXiFnosE',
    appId: '1:288364669297:ios:0b7479635eeaee1fdeeed0',
    messagingSenderId: '288364669297',
    projectId: 'iti-training-f15e2',
    storageBucket: 'iti-training-f15e2.appspot.com',
    iosClientId: '288364669297-dk5uljqg6nf93ch6ojib9t4fna9lagt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
